### ISSUE TITLE
Wrong target

### ISSUE THREAD

**Issue by Deathroner** [PikaMug/GPS-Quests#5] opened 2020-07-11 06:39 UTC
Hello, I have come to report this bug, which is causing problems on my server for delivery missions.

I noticed that having so many NPCs, GPS-Quests go crazy and send the wrong targets.

I did a cleanup of my NPCs and started loading the missions one by one, plus some stores from my server. The issue that started to fail without realizing it.

Do you think you can help us with that?

I realized that I'm not the only one

In fact I would happily pay for this plugin if you stabilize it :)

**Comment by PikaMug** [comment] 2020-09-21 17:36
Thanks for the report. Please try the latest release. If the issue still occurs, I will consider this a duplicate of #4

**Closed as completed by PikaMug** 2020-09-21 17:36 UTC
Labels: bug, duplicate
